services:
  init-data:
    image: busybox
    command: chmod -R 777 /data
    volumes:
      - election_surrealdb:/data
  election_surrealdb:
    image: surrealdb/surrealdb:v2
    command: start --user root --pass root rocksdb:/mydata/mydatabase.db
    volumes:
      - election_surrealdb:/mydata
    healthcheck:
      test: ["CMD-SHELL", "surreal", "-V"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      init-data:
        condition: service_completed_successfully
    ports:
      - 8888:8000
  rustfs:
    image: rustfs/rustfs:latest
    container_name: election-rustfs
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_CONSOLE_ENABLE=true

      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_EXTERNAL_ADDRESS=:9000 # Same as internal since no port mapping
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_OBS_LOGGER_LEVEL=info
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:9000/health && curl -f http://localhost:9001/rustfs/console/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./rustfs:/data

  mc_create_bucket:
    image: minio/mc
    depends_on:
      rustfs:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set rustfs http://rustfs:9000 rustfsadmin rustfsadmin;
      /usr/bin/mc mb rustfs/mybucket --ignore-existing;
      /usr/bin/mc anonymous set public rustfs/mybucket;
      exit 0;
      "
  election_redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    healthcheck:
      test: [CMD, redis-cli, --raw, incr, ping]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  redis_data:
  election_surrealdb:
