services:
  init-data:
    image: busybox
    command: chmod -R 777 /data
    volumes:
      - election_surrealdb:/data
  election_surrealdb:
    image: surrealdb/surrealdb:v2
    command: start --user root --pass root rocksdb:/mydata/mydatabase.db
    volumes:
      - election_surrealdb:/mydata
    healthcheck:
      test: ["CMD-SHELL", "surreal", "-V"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      init-data:
        condition: service_completed_successfully
    ports:
      - 8888:8000
  election_db:
    image: pgvector/pgvector:pg17
    container_name: election-playbook-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: election_playbook
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  election_redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    healthcheck:
      test: [CMD, redis-cli, --raw, incr, ping]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  redis_data:
  election_surrealdb:
